"""
FAQ page template definition.

Structure:
- Questions come from Question Generator Agent
- Answers generated by FAQ Generator Agent
- No logic blocks needed (content is LLM-generated)
"""

from typing import Dict, List
from src.models.templates import TemplateModel, TemplateSection


def get_faq_template() -> TemplateModel:
    """Get the FAQ page template."""
    sections = [
        TemplateSection(
            section_name="header",
            required_blocks=[],
            optional_blocks=[],
            llm_enhance=False,
            format_rules={
                "title": "Frequently Asked Questions",
                "description_template": "Common questions about {product_name}"
            }
        ),
        TemplateSection(
            section_name="questions",
            required_blocks=[],
            optional_blocks=[],
            llm_enhance=False,
            format_rules={
                "sort_by": "category",
                "max_questions": 10
            }
        ),
        TemplateSection(
            section_name="footer",
            required_blocks=[],
            optional_blocks=[],
            llm_enhance=False,
            format_rules={
                "include_contact": True,
                "include_disclaimer": True
            }
        )
    ]
    
    return TemplateModel(template_type="faq", sections=sections)


def get_faq_categories() -> List[str]:
    """Get the categories for FAQ questions."""
    return [
        "informational",
        "safety",
        "usage",
        "purchase",
        "comparison",
        "ingredients"
    ]


def get_faq_guidelines() -> Dict[str, str]:
    """Get guidelines for FAQ generation."""
    return {
        "answer_length": "2-4 sentences, 50-150 words",
        "tone": "Friendly, professional, knowledgeable",
        "accuracy": "Base answers ONLY on product information provided",
        "focus": "Address real customer concerns and common questions"
    }
